CREATE TABLE `unittest` (id INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT);
ALTER TABLE `unittest` ADD `email` VARCHAR(256)  NULL  DEFAULT NULL  AFTER `id`;
ALTER TABLE `unittest` CHANGE `email` `email` VARCHAR(256) NOT NULL;
ALTER TABLE `unittest` ADD UNIQUE INDEX (`email`);
